name: Generate platform strings

on:
  pull_request_target:
    branches:
      - master
    types:
      - closed
  push:
    branches:
      - master

jobs:
  generate:
    if: github.event_name == 'pull_request_target' && github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'
        check-latest: true

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt

    - name: execute s2t.py
      run: python s2t.py

    - uses: robinraju/release-downloader@v1.3
      with:
        repository: "MixinNetwork/handsaw"
        latest: true
        fileName: "handsaw.zip"

    - uses: montudor/action-zip@v1
      with:
        args: unzip -qq handsaw.zip -d handsaw
    - run: ./handsaw/handsaw/bin/handsaw gen -i ./client -o ./generated

    - name: Commit files
      run: |
        git config --local user.email "xxx823952375@gmail.com"
        git config --local user.name "xingstarx"
        git add generated
        git commit -m "Update generated files" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
